In [80]:
import numpy as np

## NORMALIZATION PROBLEM:

In [84]:
#Create a %x5 matrix with random numbers from 1 to 99
X = np.random.randint(low=0, high=100, size=(5, 5))
print(X)

# Use Normalization Formula
X = (X-X.mean())/X.std()

# Save it as X_normalized.npy
np.save('X_normalized.npy', X)
np.load('X_normalized.npy')

[[95 42 43 81 64]
 [96 20 24  4 12]
 [44 21 58 37  6]
 [76 16  3 57 38]
 [12 67 47 25 51]]


array([[ 1.96906702,  0.01621238,  0.05305869,  1.45321862,  0.82683128],
       [ 2.00591333, -0.79440653, -0.64702127, -1.38394755, -1.08917704],
       [ 0.08990501, -0.75756021,  0.6057534 , -0.16801919, -1.31025492],
       [ 1.26898705, -0.94179178, -1.42079387,  0.56890709, -0.13117288],
       [-1.08917704,  0.93737023,  0.20044395, -0.61017496,  0.3478292 ]])

## DIVISIBLE BY 3 PROBLEM:

In [86]:
# Create a 10x10 array with squares of the first 100 int
A = np.linspace(1,100,100).reshape(10,10)**2
# Create an empty array to be filled with digits
B = np.array([])

# Iterate every element 
for row in A:
    for element in row:
        if element%3 == 0:
            B = np.append(B, element)
        
np.save('div_by_3.npy', B)
np.load('div_by_3.npy')

array([9.000e+00, 3.600e+01, 8.100e+01, 1.440e+02, 2.250e+02, 3.240e+02,
       4.410e+02, 5.760e+02, 7.290e+02, 9.000e+02, 1.089e+03, 1.296e+03,
       1.521e+03, 1.764e+03, 2.025e+03, 2.304e+03, 2.601e+03, 2.916e+03,
       3.249e+03, 3.600e+03, 3.969e+03, 4.356e+03, 4.761e+03, 5.184e+03,
       5.625e+03, 6.084e+03, 6.561e+03, 7.056e+03, 7.569e+03, 8.100e+03,
       8.649e+03, 9.216e+03, 9.801e+03])